version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:13.2
    hostname: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Django web server
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    hostname: web
    command: /docker-entrypoint.sh
    env_file:
      - .env
    volumes:
      - ./tutorial:/app  # mount django project directory inside container
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db

volumes:
  db_data:
